# Generated by Django 5.2.1 on 2025-05-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default=None)),
                ('priority', models.IntegerField(choices=[(1, 'Extreme'), (2, 'Moderate'), (3, 'Low')], default=3)),
                ('status', models.IntegerField(choices=[(1, 'Complete'), (2, 'In Progress'), (3, 'Not Started')], default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
